name: Build and Deploy .NET App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 6.0.*
      
      - name: Cache .NET Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{runner.os}}-nuget-${{hashFiles('**/packages.lock.json')}}
          restore-keys: |
            ${{runner.os}}-nuget-
      - name: Build App
        run: dotnet build --configuration Release

      - name: Publish App
        run: dotnet publish -c Release -o ./myapp

      - name: Upload for Deployment
        uses: actions/upload-artifact@v3
        with: 
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download App From Build
        uses: actions/download-artifact@v3
        with:
          name: .net-app


  


