name: Build and Deploy .NET App

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 6
    
    - name: Cache .NET Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{runner.os}}-nuget-${{hashFiles(**/packages.lock.json)}}
        restore-keys: |
        ${{runner.os}}-nuget-
    - name: Build App
      run: dotnet build --configuration Release

    - name: Publish App
      run: dotnet publish -c Release -o ./myapp

    - name: Upload for Deployment
      uses: actions/upload-artifact@v3
        with: .net-app
        path: ./myapp

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download App From Build
          uses: actions/download-artifact@v3
           with:
            name: .net-app
        
        - name: Deploy App
          uses: azure/webapps-deploy@v2
            with:
              app-name: mydotnetapp08-06-2022
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              package: '.'


